language: go
go:
- tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  
install:
- go get -d -v ./...
deploy:
  provider: releases
  api_key:
    secure: SI6lDSW2lEhBqPprq4hsoBciIDDyTNCfJ5lM/bkOcqwtoVMh08dlyUA5y6EHSTR9q97xM4J2RHZkOkbevkQ6DfyURCB6eck1qXcUHxUGVfBn8NLmp22CDnAW169hD84nIKYjOSdrHJYUjqIK6RHMAVM9XEIzNforYfYoH1DAOwE0V5Zrany9bkKRpuFOqyZYipy4XD7VC/eCGOu4iybRLPBQQme9hcqFFniIwlW+Y+tRkGZJgbnZ5iGxWgFAu49RZbTCzF5dq1NklDNU5sST6R1naJ0cU3ljvQTffnTnzAdIz0Y8R9U4fsWuDrOeQz8XKL0i/Ngzt9oth/e/LDoSPZP36CHjPI9fNGVnCVttkYhqxWSEodkU5vEAlin2bkbnIge/OQymAg2IM5pPKZQQRZx/pYujahm6mF6LfMgxfIYPkx1gJ/2GtFTWpk5ivXbKJ9cUTTFzcQ6Jidvj0qVFdlb44KlnQkNBGeUWGX4xugEKHHzzdFIRjOXMYh5/yKFyO+fQWNprJYBxu45E09BJ1LaXlCHPJYj0Ht3uE74UqT+S3edJkZ3Rnzl5HitYwA3fSk7ofLKy+lk/gXuSpFT+iF+zG42UEaFlvCNyWrZFlY56Zp1UP9tMf4uWzlqg9rct8xmjX8PiwdSfr0lBx3+8q6tWdJ9rfPtDEzmTA58sry8=
  file:
  - release/bikemessenger-linux-amd64
  - release/bikemessenger-linux-386
  - release/bikemessenger-linux-arm
  skip_cleanup: true
  on:
    repo: delivercodes/bikemessenger
    tags: true
    all_branches: true
env:
  global:
    secure: MXuhlLNqaqGffqJww6ulqvc40rMlz+8W+iVPdNhzeYvezna9UiZ5EIvdmenYD+RliZytyoikPQ01ItE+aLFTTtzdX1RS8/ifT13Mp41RJHvQH2wtC1x3kiLkzfVTRkXs9WkXA/2pOsCjKcxmVz7msbpEiiuBOPLbkfbrbDF4xVFvet8GG9NGTepNld8hjrwkO2afPw44Ul5qlTDmj0Rg7Ec56tU6L7kjYCDoX5O4cfTR9cihf/VOlw4Agawl4ZKfOJxv6uuT0SAlelsYfRsa8ievLQIv5uHYjqOhZ77BVDs632pAcEv5rU4D3V7kAZuqb1dph4agR9m9Xgq7usr0QMHh/iTJ2Q9rMuBm7TsnqqrLdNFZtP9Fn9F2PbFFfq18pPmngAg2EGI6EPlOTLGJ+If8S25nE6cxk9fe8/egEU71ub6lO/8D3QB4r4T8nhEfPM8U3RU0H6JSfsIJfjCqaGMzwXDzHlrpgwpwTGHtlAlIOgElck8/pQhuRQOaNkLj2qie8BrvPXZkMfs0GHS8yTRxwa47m+gtYf+ddaDkJlDLu8FXXgYSRDoI+l6lseUVwHhl6o25u+TTpozMIW3CDp+3VOKRhllU8BJXgpQatjFRzPkfo+7HTEWJqcJPyRiOJSaD5WkHfuD6wR/hiyoZ/ysHne5dRIMCvZkEMUwbUh0=
