language: go
sudo: false
go:
- tip
before_install:
  - go get github.com/mattn/goveralls
  - go get -d -v ./...
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
deploy:
  provider: releases
  api_key:
    secure: SI6lDSW2lEhBqPprq4hsoBciIDDyTNCfJ5lM/bkOcqwtoVMh08dlyUA5y6EHSTR9q97xM4J2RHZkOkbevkQ6DfyURCB6eck1qXcUHxUGVfBn8NLmp22CDnAW169hD84nIKYjOSdrHJYUjqIK6RHMAVM9XEIzNforYfYoH1DAOwE0V5Zrany9bkKRpuFOqyZYipy4XD7VC/eCGOu4iybRLPBQQme9hcqFFniIwlW+Y+tRkGZJgbnZ5iGxWgFAu49RZbTCzF5dq1NklDNU5sST6R1naJ0cU3ljvQTffnTnzAdIz0Y8R9U4fsWuDrOeQz8XKL0i/Ngzt9oth/e/LDoSPZP36CHjPI9fNGVnCVttkYhqxWSEodkU5vEAlin2bkbnIge/OQymAg2IM5pPKZQQRZx/pYujahm6mF6LfMgxfIYPkx1gJ/2GtFTWpk5ivXbKJ9cUTTFzcQ6Jidvj0qVFdlb44KlnQkNBGeUWGX4xugEKHHzzdFIRjOXMYh5/yKFyO+fQWNprJYBxu45E09BJ1LaXlCHPJYj0Ht3uE74UqT+S3edJkZ3Rnzl5HitYwA3fSk7ofLKy+lk/gXuSpFT+iF+zG42UEaFlvCNyWrZFlY56Zp1UP9tMf4uWzlqg9rct8xmjX8PiwdSfr0lBx3+8q6tWdJ9rfPtDEzmTA58sry8=
  file:
  - release/bikemessenger-linux-amd64
  - release/bikemessenger-linux-386
  - release/bikemessenger-linux-arm
  skip_cleanup: true
  on:
    repo: delivercodes/bikemessenger
    tags: true
    all_branches: true
