services:
    postgres:
        env:
            - DEBUG=2
        image: postgres
        ports:
            - 8660:80
            - 443:443
    cherubini_casa:
        image: docker.cherubini.casa/cherubini_nginx:2
        ports:
            - 9000:80
            - 9443:443
