services:
    alpine:
        image: alpine
        env:
            - DEBUG=2
        ports:
            - 8660:80
            - 7443:443
    node:
        image: iron/node
        env:
            - DEBUG=1
        ports:
            - 9990:80
            - 8443:443
